"""Ontology indexer agent for vector-searchable ontology terms."""

from __future__ import annotations

import hashlib
import json
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import requests

from app.agents import get_model_for_task
from app.db.sqlite import get_db

_URL_RE = re.compile(r"https?://[^\s)>\"]+")


@dataclass(frozen=True)
class ParsedOntologyTerm:
    label: str
    description: str
    uri: str
    properties: dict[str, list[str]]


class OntologyIndexerAgent:
    """Fetch ontology terms, embed them, and store versioned snapshots."""

    def run(
        self,
        description: str,
        llm_client: Any = None,
        *,
        source_id: int | None = None,
        source_name: str | None = None,
    ) -> dict[str, Any]:
        urls = self._extract_urls(description)
        rdf_urls = [url for url in urls if self._looks_like_rdf_or_owl(url)]
        doc_urls = [url for url in urls if url not in rdf_urls]

        terms: list[ParsedOntologyTerm] = []
        for rdf_url in rdf_urls:
            rdf_text = self._fetch_text(rdf_url)
            if not rdf_text:
                continue
            terms.extend(self._parse_rdf_terms(rdf_text, rdf_url))

        if not terms:
            terms = self._parse_text_description(description)

        db = get_db()
        ontology_name = source_name or self._infer_ontology_name(description, rdf_urls)
        if source_id is None:
            source_cursor = db.execute(
                "INSERT INTO ontology_sources (name, description, rdf_url, documentation_url)"
                " VALUES (?, ?, ?, ?)",
                (
                    ontology_name,
                    description,
                    rdf_urls[0] if rdf_urls else None,
                    doc_urls[0] if doc_urls else None,
                ),
            )
            assert source_cursor.lastrowid is not None
            source_id = int(source_cursor.lastrowid)

        embedding_model = get_model_for_task("ontology_embedding")
        version_cursor = db.execute(
            "INSERT INTO ontology_index_versions (source_id, embedding_model, status, notes)"
            " VALUES (?, ?, 'running', ?)",
            (
                source_id,
                embedding_model,
                "Auto-generated by OntologyIndexerAgent",
            ),
        )
        assert version_cursor.lastrowid is not None
        version_id = int(version_cursor.lastrowid)
        db.commit()

        if terms:
            embeddings = self._embed_terms(terms, llm_client)
            for term, embedding in zip(terms, embeddings):
                db.execute(
                    "INSERT INTO ontology_terms (source_id, version_id, label, description, uri, ontology_name, properties_json, embedding_json)"
                    " VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
                    " ON CONFLICT(version_id, uri) DO UPDATE SET"
                    "   label = excluded.label,"
                    "   description = excluded.description,"
                    "   ontology_name = excluded.ontology_name,"
                    "   properties_json = excluded.properties_json,"
                    "   embedding_json = excluded.embedding_json,"
                    "   updated_at = datetime('now')",
                    (
                        source_id,
                        version_id,
                        term.label,
                        term.description,
                        term.uri,
                        ontology_name,
                        json.dumps(term.properties, ensure_ascii=False),
                        json.dumps(embedding),
                    ),
                )

        db.execute(
            "UPDATE ontology_index_versions SET status = 'ready', is_active = 0 WHERE source_id = ?",
            (source_id,),
        )
        db.execute(
            "UPDATE ontology_index_versions SET is_active = 1, status = 'ready' WHERE id = ?",
            (version_id,),
        )
        db.execute(
            "UPDATE ontology_sources"
            " SET active_version_id = ?,"
            "     description = ?,"
            "     rdf_url = coalesce(?, rdf_url),"
            "     documentation_url = coalesce(?, documentation_url),"
            "     last_indexed_at = datetime('now'),"
            "     updated_at = datetime('now')"
            " WHERE id = ?",
            (
                version_id,
                description,
                rdf_urls[0] if rdf_urls else None,
                doc_urls[0] if doc_urls else None,
                source_id,
            ),
        )
        db.commit()

        return {
            "source_id": source_id,
            "version_id": version_id,
            "ontology_name": ontology_name,
            "indexed_terms": len(terms),
            "embedding_model": embedding_model,
        }

    def _extract_urls(self, text: str) -> list[str]:
        return [match.group(0).strip(".,") for match in _URL_RE.finditer(text)]

    def _looks_like_rdf_or_owl(self, url: str) -> bool:
        lowered = url.lower()
        return lowered.endswith((".rdf", ".owl", ".ttl", ".xml", ".nt")) or any(
            token in lowered for token in ("/rdf", "/owl", "sparql")
        )

    def _fetch_text(self, url: str) -> str | None:
        try:
            response = requests.get(url, timeout=20)
        except requests.RequestException:
            return None
        if not response.ok:
            return None
        return response.text

    def _parse_rdf_terms(self, rdf_text: str, source_url: str) -> list[ParsedOntologyTerm]:
        try:
            root = ET.fromstring(rdf_text)
        except ET.ParseError:
            return []

        terms: list[ParsedOntologyTerm] = []
        seen: set[str] = set()
        for node in root.iter():
            uri = self._extract_node_uri(node, source_url)
            if not uri or uri in seen:
                continue
            properties = self._extract_node_properties(node)
            if not properties:
                continue
            label = self._first_property_value(
                properties, ("label", "prefLabel", "title", "name")
            ) or uri.rsplit("/", 1)[-1].rsplit("#", 1)[-1]
            description = self._first_property_value(
                properties,
                ("description", "comment", "definition", "IAO_0000115"),
            )
            if not description:
                description = "; ".join(
                    f"{key}: {', '.join(values)}" for key, values in properties.items() if values
                )
            terms.append(
                ParsedOntologyTerm(
                    label=label.strip(),
                    description=description.strip(),
                    uri=uri,
                    properties=properties,
                )
            )
            seen.add(uri)
        return terms

    def _extract_node_uri(self, node: ET.Element, source_url: str) -> str | None:
        for attr_name, attr_value in node.attrib.items():
            lowered = attr_name.lower()
            if lowered.endswith("about") or lowered.endswith("resource") or lowered.endswith("id"):
                if attr_value.startswith("http://") or attr_value.startswith("https://"):
                    return attr_value
                if attr_value.startswith("#"):
                    return f"{source_url}{attr_value}"
                if attr_value:
                    return f"{source_url.rstrip('/')}/{attr_value.lstrip('/')}"
        return None

    def _extract_node_properties(self, node: ET.Element) -> dict[str, list[str]]:
        properties: dict[str, list[str]] = {}
        for child in list(node):
            text = (child.text or "").strip()
            if not text:
                continue
            key = child.tag.rsplit("}", 1)[-1]
            properties.setdefault(key, []).append(text)
        return properties

    def _first_property_value(
        self, properties: dict[str, list[str]], candidates: tuple[str, ...]
    ) -> str | None:
        lowered = {key.lower(): values for key, values in properties.items()}
        for candidate in candidates:
            values = lowered.get(candidate.lower())
            if values:
                return values[0]
        return None

    def _parse_text_description(self, description: str) -> list[ParsedOntologyTerm]:
        terms: list[ParsedOntologyTerm] = []
        for index, line in enumerate(description.splitlines()):
            clean_line = line.strip().lstrip("-*")
            if ":" not in clean_line:
                continue
            label, desc = clean_line.split(":", 1)
            label = label.strip()
            desc = desc.strip()
            if not label or not desc:
                continue
            uri_hash = hashlib.sha1(f"{label}-{index}".encode()).hexdigest()[:12]
            uri = f"urn:ontology:text:{uri_hash}"
            terms.append(
                ParsedOntologyTerm(
                    label=label,
                    description=desc,
                    uri=uri,
                    properties={"text_description": [desc]},
                )
            )
        if terms:
            return terms

        fallback = description.strip()
        if not fallback:
            return []
        uri_hash = hashlib.sha1(fallback.encode()).hexdigest()[:12]
        return [
            ParsedOntologyTerm(
                label=fallback[:80],
                description=fallback,
                uri=f"urn:ontology:text:{uri_hash}",
                properties={"text_description": [fallback]},
            )
        ]

    def _embed_terms(self, terms: list[ParsedOntologyTerm], llm_client: Any) -> list[list[float]]:
        texts = [
            "\n".join(
                [
                    term.label,
                    term.description,
                    json.dumps(term.properties, ensure_ascii=False),
                ]
            )
            for term in terms
        ]
        if llm_client is not None:
            try:
                result = llm_client.embeddings.create(
                    model=get_model_for_task("ontology_embedding"),
                    input=texts,
                )
                data = getattr(result, "data", [])
                if isinstance(data, list) and len(data) == len(texts):
                    vectors: list[list[float]] = []
                    for row in data:
                        embedding = getattr(row, "embedding", None)
                        if isinstance(embedding, list):
                            vectors.append([float(value) for value in embedding])
                    if len(vectors) == len(texts):
                        return vectors
            except Exception:
                pass

        return [self._fallback_embedding(text) for text in texts]

    def _fallback_embedding(self, text: str) -> list[float]:
        digest = hashlib.sha256(text.encode()).digest()
        return [byte / 255.0 for byte in digest]

    def _infer_ontology_name(self, description: str, rdf_urls: list[str]) -> str:
        lowered = description.lower()
        if "edam" in lowered:
            return "EDAM"
        if "panet" in lowered:
            return "PaNET"
        if rdf_urls:
            url = rdf_urls[0]
            domain = re.sub(r"^https?://", "", url).split("/", 1)[0]
            return domain or "Ontology"
        return f"Ontology-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
